# Generated by Django 5.2.1 on 2025-06-08 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.CharField(blank=True, choices=[('A1', 'Grade A1'), ('A2', 'Grade A2'), ('B1', 'Grade B1'), ('B2', 'Grade B2'), ('B3', 'Grade B3')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('Hod', 'Hod'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Compensator', 'Compensator')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_department', models.CharField(max_length=100)),
                ('HOD', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='core.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department'),
        ),
    ]
