# Generated by Django 5.2.1 on 2025-06-10 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_grade_employee_role_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('note', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('proof', models.FileField(upload_to='expense_proofs/')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('L1', 'L1'), ('HoD', 'HoD')], max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.expense')),
                ('required_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='core.employee')),
            ],
        ),
    ]
