# Generated by Django 5.2.3 on 2025-06-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expense_expenserequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('department_id', models.IntegerField()),
                ('limit_amount', models.IntegerField()),
                ('duration', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=10)),
                ('policy_type', models.CharField(choices=[('Hard', 'Hard'), ('Soft', 'Soft')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
