# Generated by Django 5.2.3 on 2025-06-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_policy_alter_expenserequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='grade',
        ),
    ]
