# Generated by Django 5.2.3 on 2025-06-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_policy_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='grade',
            field=models.CharField(blank=True, choices=[('A1', 'Grade A1'), ('A2', 'Grade A2'), ('B1', 'Grade B1'), ('B2', 'Grade B2'), ('B3', 'Grade B3')], max_length=2, null=True),
        ),
    ]
