# Generated by Django 5.2.3 on 2025-06-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_expense_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='reason_for_hod',
            field=models.TextField(blank=True, null=True),
        ),
    ]
