# Generated by Django 5.2.3 on 2025-06-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_expenserequest_reason_for_hod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserequest',
            name='reason_for_hod',
        ),
        migrations.AddField(
            model_name='expense',
            name='reason_for_hod',
            field=models.TextField(blank=True, null=True),
        ),
    ]
