# Generated by Django 5.2.3 on 2025-06-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_expense_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='priority',
            field=models.IntegerField(choices=[('1', 'Higher Priority'), ('2', 'Lower Priority')], default=2),
        ),
    ]
