# Generated by Django 5.2.3 on 2025-06-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_policy_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Higher Priority'), (2, 'Lower Priority')], default=1),
        ),
    ]
