# Generated by Django 5.2.3 on 2025-07-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_policy_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='department_id',
            new_name='department',
        ),
    ]
