# Generated by Django 5.2.3 on 2025-07-03 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_department_id_policy_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='core.department'),
        ),
    ]
