name: Deploy Expense Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: http://172.198.74.181:5173

    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            cd ~/Expense_project
            git pull origin main
            docker compose up -d --build
